# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20171016_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='ratings',
            new_name='vote_average',
        ),
    ]
